src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $username = null;

    #[ORM\Column(length: 80)]
    private ?string $email = null;

    #[ORM\Column(length: 80)]
    private ?string $password = null;

	#[ORM\Column(length: 80)]
	private ?string $role = null;

    /**
     * @var Collection<int, Posts>
     */
    #[ORM\OneToMany(targetEntity: Posts::class, mappedBy: 'author')]
    private Collection $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Posts $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

}

src/Controller/AboutController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class AboutController extends AbstractController
{
    #[Route('/about', name: 'app_about')]
    public function index(): Response
    {
        return $this->render('about/index.html.twig', [
            'controller_name' => 'AboutController',
			'page_name' => 'Tentang Saya',
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
//use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Posts;
use App\Repository\PostsRepository;

final class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(PostsRepository $repository, Request $req): Response
    {
		$curPage = $req->query->getInt('page', 1);
		$limit = 8;

		$paginator = $repository->getAllPaginated($curPage, $limit);
		$totalPage = ceil($repository->getTotalPost() / $limit);
		$totalPost = $repository->getTotalPost();


        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
			'page_name' => 'Beranda',
			'paginator' => $paginator,
			'total_page' => $totalPage,
			'cur_page' => $curPage,
			'limit' => $limit,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
//use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Posts;
use App\Repository\PostsRepository;

final class PostsController extends AbstractController
{
    #[Route('/posts', name: 'app_posts')]
    public function index(PostsRepository $repository, Request $req): Response
    {
		$curPage = $req->query->getInt('page', 1);
		$limit = 10;

		$paginator = $repository->getAllPaginated($curPage, $limit);
		$totalPage = ceil($repository->getTotalPost() / $limit);

        return $this->render('posts/index.html.twig', [
            'controller_name' => 'PostsController',
			'page_name' => 'Tulisan',
			'paginator' => $paginator,
			'total_page' => $totalPage,
			'cur_page' => $curPage,
			'limit' => $limit,
        ]);
    }

    #[Route('/posts/{id}', name: 'app_post_content')]
	public function content(EntityManagerInterface $entityManager, int $id): Response
	{
		$post = $entityManager->getRepository(Posts::class)->find($id);

		return $this->render('posts/content.html.twig', [
			'page_name' => 'Isi Tulisan',
			'post' => $post,
		]);
	}
}

templates/about/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1 class="title is-1">{{ page_name }}</h1>

<div class="card my-6">
<div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-128x128">
          <img
            src="https://bulma.io/assets/images/placeholders/96x96.png"
            alt="Placeholder image"
          />
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">Ocak</p>
        <p class="subtitle is-6">@ocakaco</p>
      </div>
    </div>

    <div class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec
      iaculis mauris.
    </div>
  </div>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Ocaka | {{ page_name }}</title>
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
		<div class="is-flex is-flex-direction-column is-full-height-100vh">
		{% block header %}
		<div class="is-flex is-align-items-flex-start">
			<nav class="navbar pb-5" role="navigation" aria-label="main navigation">
			  <div class="navbar-brand">
				<a class="navbar-item" href="{{ path('app_home') }}">
					<h1>Ocaka</h1>
				</a>

				<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
				  <span aria-hidden="true"></span>
				  <span aria-hidden="true"></span>
				  <span aria-hidden="true"></span>
				  <span aria-hidden="true"></span>
				</a>
			  </div>

			  <div id="navbarBasicExample" class="navbar-menu">
				<div class="navbar-start">
				  <a class="navbar-item is-selected" href="{{ path('app_home') }}">
					Beranda
				  </a>

				  <div class="navbar-item has-dropdown is-hoverable">
					<a class="navbar-link" href="{{ path('app_posts') }}">
					  Tulisan
					</a>

					<div class="navbar-dropdown">
					  <a class="navbar-item" href="{{ path('app_posts') }}">
						Cerpen
					  </a>
					  <a class="navbar-item">
						Artikel
					  </a>
					  <a class="navbar-item">
						How-to
					  </a>
					  <hr class="navbar-divider">
					  <a class="navbar-item">
						Report an issue
					  </a>
					</div>
				  </div>

				  <a class="navbar-item" href="{{ path('app_about') }}">
					Tentang Saya
				  </a>
				</div>
			</div>

			<!-- Tombol daftar/login (belum perlu)
			<div class="navbar-end">
			  <div class="navbar-item">
				<div class="buttons">
				  <a class="button is-primary">
					<strong>Sign up</strong>
				  </a>
				  <a class="button is-light">
					Log in
				  </a>
				</div>
			  </div>
			</div>
			-->
		  </div>
		</nav>
		{% endblock %}

		<div class="container is-fullhd">
        {% block body %}{% endblock %}
		</div>

		{% block footer %}
		<footer class="footer is-flex is-align-items-flex-end is-justify-content-center">
		  <div class="content has-text-centered">
			<p>
			  <strong>Ocaka</strong> by <a href="{{ path('app_about') }}">Ocak</a>.
			</p>
		  </div>
		</footer>
		{% endblock %}
		</div>
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1 class="title is-1">{{ page_name }}</h1>

<div class="fixed-grid has-4-cols">
<div class="grid">
	{% for post in paginator %}
		<div class="card cell m-2">
		  <div class="card-image">
			<a href="{{ path('app_post_content', {id: post.id}) }}">
			<figure class="image is-4by3">
			  <img
				src="https://bulma.io/assets/images/placeholders/640x480.png"
				alt="Placeholder image"
			  />
			</figure>
			</a>
		  </div>
		  <div class="card-content">
			<div class="media">
			  <div class="media-content">
				<a class="title is-4" href="{{ path('app_post_content', {id: post.id}) }}">{{ post.title }}</a>
				<p class="subtitle is-6">by {{ post.author.username }}</p>
			  </div>
			</div>

			<div class="content">
			  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
			   <a href="{{ path('app_post_content', {id: post.id}) }}">read more...</a>
			  <br />
			  <time>{{ post.createdAt|date('H:i - j F Y') }}</time>
			</div>
		  </div>
		</div>
	{% endfor %}
</div>
</div>


<!-- Pagination -->
<nav class="pagination is-centered my-5" role="navigation" aria-label="pagination">

  {% if cur_page != 1 %}
  <a href="?page={{ cur_page - 1 }}" class="pagination-previous">Previous</a>
  {% else %}
  <a href="?page={{ cur_page - 1 }}" class="pagination-previous is-disabled">Previous</a>
  {% endif %}

  {% if cur_page != total_page %}
  <a href="?page={{ cur_page + 1 }}" class="pagination-next">Next page</a>
  {% else %}
  <a href="?page={{ cur_page + 1 }}" class="pagination-next is-disabled">Next page</a>
  {% endif %}

  {% if total_page != 1 %}
  <ul class="pagination-list">
	{% for i in 1..total_page %}
	<li>
	  {% if i == cur_page %}
	  <a href="?page={{ i }}" class="pagination-link is-disabled" aria-label="">{{ i }}</a>
	  {% else %}
	  <a href="?page={{ i }}" class="pagination-link" aria-label="">{{ i }}</a>
	  {% endif %}
	</li>
	{% endfor %}
  </ul>
  {% endif %}

</nav>

{% endblock %}

templates/post_content/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="content py-6">
  <h1>Lorem Ipsum</h1>
  <small>created by Ocak at </small>
  <figure>
    <img src="https://bulma.io/assets/images/placeholders/256x256.png" />
    <figcaption>Figure 1: Some beautiful placeholders</figcaption>
  </figure>
  <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.</p>
</div>

{% endblock %}

templates/posts/content.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{# dump(post) #}
<div class="content py-6">
  <h1>Lorem Ipsum</h1>
  <small>created by Ocak at </small>
  <figure>
    <img src="https://bulma.io/assets/images/placeholders/256x256.png" />
    <figcaption>Figure 1: Some beautiful placeholders</figcaption>
  </figure>
  <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.</p>
</div>

{% endblock %}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="py-6">
<h1 class="title is-1">{{ page_name }}</h1>
{#dump(posts[0].createdAt)#}

{% for post in paginator %}
<div class="box">
  <article class="media">
    <div class="media-left">
	  <a href="{{ path('app_post_content', {id: post.id}) }}">
      <figure class="image is-128x128">
        <img src="https://bulma.io/assets/images/placeholders/128x128.png" alt="Image" />
      </figure>
	  </a>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><a href="{{ path('app_post_content', {id: post.id}) }}">{{ post.title }}</a></strong>
		  <br />
          <small>by {{ post.author.username }} | {{ post.createdAt|date('Y-m-d H:i') }}</small>
          <br />
          <br />
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean
          efficitur sit amet massa fringilla egestas. Nullam condimentum luctus
          turpis... <a href="{{ path('app_post_content', {id: post.id}) }}">read more</a>
        </p>
      </div>
    </div>
  </article>
</div>
{% endfor%}

</div>

<!-- Pagination -->
<nav class="pagination is-centered my-5" role="navigation" aria-label="pagination">

  {% if cur_page != 1 %}
  <a href="?page={{ cur_page - 1 }}" class="pagination-previous">Previous</a>
  {% else %}
  <a href="?page={{ cur_page - 1 }}" class="pagination-previous is-disabled">Previous</a>
  {% endif %}

  {% if cur_page != total_page %}
  <a href="?page={{ cur_page + 1 }}" class="pagination-next">Next page</a>
  {% else %}
  <a href="?page={{ cur_page + 1 }}" class="pagination-next is-disabled">Next page</a>
  {% endif %}

  {% if total_page != 1 %}
  <ul class="pagination-list">
	{% for i in 1..total_page %}
	<li>
	  {% if i == cur_page %}
	  <a href="?page={{ i }}" class="pagination-link is-disabled" aria-label="">{{ i }}</a>
	  {% else %}
	  <a href="?page={{ i }}" class="pagination-link" aria-label="">{{ i }}</a>
	  {% endif %}
	</li>
	{% endfor %}
  </ul>
  {% endif %}

</nav>

{% endblock %}